import { motion } from "framer-motion"
import ReactMarkdown from "react-markdown"

interface ArticleViewProps {
    title: string
    content: string
}

export function ArticleView({ title, content }: ArticleViewProps) {
    return (
        <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="max-w-3xl mx-auto bg-[#f8f5f2] text-slate-900 rounded-sm shadow-2xl p-12 min-h-screen my-12 relative overflow-hidden"
        >
            {/* Paper Texture Overlay */}
            <div className="absolute inset-0 opacity-[0.03] pointer-events-none bg-[url('https://www.transparenttextures.com/patterns/cream-paper.png')] mix-blend-multiply"></div>

            <article className="prose prose-slate prose-lg md:prose-xl mx-auto font-serif">
                <h1 className="font-serif text-5xl font-bold mb-8 tracking-tight text-slate-900 text-center border-b-2 border-slate-900 pb-8">
                    {title}
                </h1>

                <div className="markdown-body leading-relaxed text-slate-800">
                    {/* Simple whitespace handling if not using full markdown parser currently, 
               but ideally use react-markdown here. For now, simple render. 
           */}
                    <ReactMarkdown>{content}</ReactMarkdown>
                </div>

                <div className="mt-16 pt-8 border-t border-slate-300 text-center text-slate-500 text-sm italic font-sans">
                    Generated by LitAgent • AI Authored
                </div>
            </article>
        </motion.div>
    )
}
